import "@/styles/globals.css";
import type { Metadata } from "next";
import { fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import { SiteHeader } from "@/components/site-header";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SolanaWalletProvider } from "@/components/providers/wallet-provider";
import { ConfigProvider } from "@/components/providers/config-account-provider";
import { CollateralProvider } from "@/components/providers/collateral-account-provider";
import { PythPriceProvider } from "@/components/providers/pyth-pricefeed-provider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <SolanaWalletProvider>
          <ConfigProvider>
            <CollateralProvider>
              <PythPriceProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  forcedTheme="dark"
                  enableSystem
                  disableTransitionOnChange
                >
                  <div className="relative flex min-h-screen flex-col">
                    <SiteHeader />
                    <div className="flex-1">{children}</div>
                    <Toaster />
                  </div>
                </ThemeProvider>
              </PythPriceProvider>
            </CollateralProvider>
          </ConfigProvider>
        </SolanaWalletProvider>
        <TailwindIndicator />
      </body>
    </html>
  );
}
