import "./globals.css";
import { ClusterProvider } from "@/components/cluster/cluster-data-access";
import { SolanaProvider } from "@/components/solana/solana-provider";
import { UiLayout } from "@/components/ui/ui-layout";
import { ReactQueryProvider } from "./react-query-provider";

export const metadata = {
  title: "dapp-token-vesting",
  description: "Generated by create-solana-dapp",
};

const links: { label: string; path: string }[] = [
  { label: "Account", path: "/account" },
  { label: "Clusters", path: "/clusters" },
];
const companyLinks: { label: string; path: string }[] = [
  { label: "Token Program", path: "/mint" },
  { label: "Vesting Program", path: "/dapptokenvesting" },
  { label: "Vested Employees", path: "/vestedemployees" },
];
const employeeLinks: { label: string; path: string }[] = [
  { label: "Claim Token", path: "/employeetoken" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1"
      />
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <UiLayout
                links={links}
                companyLinks={companyLinks}
                employeeLinks={employeeLinks}
              >
                {children}
              </UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
